require 'rake/clean'

CLEAN.include(FileList['*.html','*.pdf','*.png'])

# Windows has a name clash with builtin dos convert command
cov = if ENV.has_key? 'CONVERT' then 
          "\"#{ENV['CONVERT']}\"" 
      else 
          "convert" 
      end

task :default => ['slides.html','notes.pdf']

rule '.png' => '.gnu' do |t|
    sh "gnuplot #{t.source}"
end

rule '.png' => '.svg' do |t|
    sh "#{cov} #{t.source} #{t.name}"
end

file 'slides.html' => 'slides.markdown' do
    sh "pandoc -w s5 -s slides.markdown > slides.html"
end

file 'languages.png' => 'language-study.list' do
    sh "perl language-study.list2dot language-study.list | dot -Tpng > languages.png"
end

file 'notes.pdf' => 'notes.markdown' do
    sh "markdown2pdf -N -o notes.pdf notes.markdown"
end

file 'slides.markdown' => [ 
    'lazy-eager-single-multi.png',
    'dynamic-static-strong-weak.png',
    'languages.png', 
    'parabola.png', 
    'curve.png'
]
file 'notes.markdown' => []
