require 'rake/clean'

CLEAN.include(FileList['*.html','*.pdf','*.png'])

task :default => ['slides.html','notes.pdf']

rule '.png' => '.gnu' do |t|
    sh "gnuplot #{t.source}"
end

file 'slides.html' => 'slides.markdown' do
    sh "pandoc -w s5 -s slides.markdown > slides.html"
end

file 'languages.png' => 'language-study.list' do
    sh "perl language-study.list2dot language-study.list | dot -Tpng > languages.png"
end

file 'notes.pdf' => 'notes.markdown' do
    sh "markdown2pdf -N -o notes.pdf notes.markdown"
end

file 'slides.markdown' => ['languages.png', 'parabola.png']
file 'notes.markdown' => []
